### ISSUE TITLE
non funziona

### ISSUE THREAD

**Issue by geass88** [hearot/ArgoScuolaNext-Python#2]
sto provando ad utilizzare sia l'api PHP che quella python ma non funziona ... la versione di scuolanext è 4.0.1, sto usando come codice scuola quello riportato sulla barra di stato in fondo alla pagina scuola next e le credenziali quelle con cui accedo... ma nulla

**Comment by hearot** [comment]
Buonasera, leggo solamente adesso; alla fine ha risolto?
